### ISSUE TITLE
How to store the dicom file on HDFS?

### ISSUE THREAD

**Issue by hellotod** [MarcoLotz/HadoopLung#1]
AS TITLE

**Comment by MarcoLotz** [comment]
as any other file. [...] copyFromLocal [file name] [ ...]

**Comment by hellotod** [comment]
Thank you for your reply.
1. I still  have  a doubt,  i mean a  dicom file is not up to 128MB.  The minimum size of each block is 128MB. how to store  CT/MR scanning sequences. 
2. The program can handle CT or MR scan sequences? Or it only supports processing DR data.

**Comment by MarcoLotz** [comment]
1. I guess I understood what you mean. If I am not wrong, you can reduce the HDFS block site in the .xml configurations. The HDFS space usage is different from the block usage. Thus, if you put a file much smaller than a block, you will not use 128 megabytes of your file system.

More information about this can found in a Tom White post at cloudera webpage, called "Small Files Problem"
In my case, I kept them as 128 MB. This causes the small file problem, that I solved by this special InputFormat class that I wrote:

https://github.com/MarcoLotz/HadoopLung/blob/master/src/com/marcolotz/lung/io/inputFormat/MultipleFilesInputFormat.java 

Got a speedup of 20 times with this input format.
1. I used only for CT scans, but it can be easily extended for other types/formats. It can be used for sequences as longs as the Mapper part operate in a slice independent way (i.e. one DICOM file do not depend, on mapper moment, of the result of the another in the sequence). The sequence ordering/special processing is done based on the DICOM UID of the "exam", in the reducer. Thus, all slices that compose a sequence of the same exam are grouped in the reducers.
2. Should you extend the code, please commit to this repo and reference the original one. Am really interested in other brilliant life-saver solutions using the opensource version of my application :) The code is under CC license.

More info on:
http://stackoverflow.com/questions/11368907/hadoop-block-size-and-file-size-issue

**Comment by Cassie-CV** [comment]
How to write  result of HadoopLung  as BMP or JPG, not json file?
