### ISSUE TITLE
How do you analyze pulmonary nodules

### ISSUE THREAD

**Issue by hellotod** [MarcoLotz/HadoopLung#2]
Hi MarcoLotz，
As the title , and Which open source JAR package is used? 
CAD used?

**Comment by MarcoLotz** [comment]
Hi there,

The nodule detection is done on the lung processor and post processor, using DICOM threshold, 3D morphology and segmentation analysis. Parts of the lung processor project are used as a plug in on the hadoop lung code. The output of hadoop lung is ingested on the post processor part.

I have a few slides explaining a bit of the operation in English if you rather. Also have a complete in detail thesis about it in portuguese, about 150 pages. What are you developing exactly?

Cheers,
Marco

**Comment by MarcoLotz** [comment]
Forgot to answer the last part. Yes. It's a plugin-extensible computer aided diagnosis tool, aiming not to give a ground truth diagnosis, but to provide multiple interpretation scenarios/infos for doctors.
