### ISSUE TITLE
How to write result of HadoopLung as BMP or JPG, not json file?

### ISSUE THREAD

**Issue by Cassie-CV** [MarcoLotz/HadoopLung#3]
Hello，as the title, how to write result of HadoopLung as BMP or JPG, not json file?

**Comment by MarcoLotz** [comment]
First, you need to modify the output of the mapper to produce images instead of image metadata. This can be done by writting a new output for the lung processor. Keep in mind that having images coming out of the mapper is network intensive when compared with imagemetada.

Finally, you need to make sure that the reducer does image -> image and not imagemetadata -> list[imagemetada].

**Comment by Cassie-CV** [comment]
Thank you very much~

**Comment by Cassie-CV** [comment]
Hi, I want to know that how to produce images from DICOM?

**Comment by MarcoLotz** [comment]
You mean how to translate a DICOM file into a BMP or JPG file? If so, probably you can convert using ImageJ libraries.

**Comment by Cassie-CV** [comment]
Using DICOM image（image data and image metadata）as  the output of Mapper and Reducer,  is it OK?

**Comment by chok68** [comment]
Hi @MarcoLotz,

How does this work? Wonder if there's a tutorial or some doc around.

Thanks

**Comment by MarcoLotz** [comment]
@chok68 You should launch it as a normal MapReduce job.

Just launch a MapReduce job where the entry point is the LungDriver.java:
https://github.com/MarcoLotz/HadoopLung/blob/master/src/main/java/com/marcolotz/lung/mapreduce/MRCore/LungDriver.java

You can see that this class reads a configuration file in the "conf" folder. There you can specify the path where your files are stored in HDFS and other features.

There is an extensive documentation, including the algorithms used for the detection, on this document: http://www.marcolotz.com/wp-content/uploads/2014/10/2014a_PF2_MarcoABFGLotz.pdf
It is in Portuguese, however. You can use google translator to get the gist behind it.

Cheers,
Marco

**Comment by chok68** [comment]
Thanks @MarcoLotz this info helps a lot! ...btw I speak spanish so not very difficult to follow along the doc :)

**Comment by MarcoLotz** [comment]
@chok68 Muy bien! If you need any further information just drop me a line on my e-mail contact (at) marcolotz (dot) com
